### ISSUE TITLE
Interactive interface is too primitive for long term use

### ISSUE THREAD

**Issue by drakes00** [nccgroup/featherduster#15]
Hi, I might be interested in working on autocompletion on inputs (filenames and/or paths)?
Would you be interested?
On the tip of my head I was going for the rlcompleter and readline packages that might introduce new dependencies (not sure).
Do you have a better idea of how to do it?

Cheers

**Comment by unicornsasfuel** [comment]
I love the idea and was thinking along the same lines, but I want to minimize dependencies as much as possible. However, I recognize that the CLI is extremely limited as of right now and really needs to improve. I think, considering the importance of the interface, I'm okay with adding another dependency. In the same way that we can't really build a cryptanalysis framework without a multi-precision integer library, we can't build a menu-driven interface without a decent menu library.

There are a couple things I want out of a menu library:

* OS independence
* Autocompletion
* Simplicity of use

I haven't yet found a menu library that supports all this, perhaps it would make sense to create one if we can't find a good one. Something to think about, anyway.

**Comment by unicornsasfuel** [comment]
So [ishell](https://github.com/italorossi/ishell) looks like it fits the bill on all counts.

What are your thoughts?

**Comment by drakes00** [comment]
Sounds interesting however it seems to me that it only provides autocompletion for commands and not paths, isn't it?
It could maybe be combined with glob: https://docs.python.org/2/library/glob.html

**Comment by unicornsasfuel** [comment]
I was thinking along similar lines. We could either use `glob.glob()` or `os.listdir()` to populate an autocompletion list like so:

```
import os
from ishell.console import Console
from ishell.command import Command

class Test(Command):
   def args(self):
      return os.listdir('.')
   def run(self,line):
      print 'You selected the file ' + line.split()[-1]

test = Test('test', help='Select a file', dynamic_args=True)

console = Console(prompt='test prompt v0.0.0.1beta', prompt_delim='>')
console.addChild(test)
console.loop()
```

We could probably also have a command to change the working directory, but I'm not sure how to do autocomplete on file paths on a path item basis a la bash. I think we might be able to overwrite Command.complete(), but there's not much documentation on doing so and Command.args() doesn't involve the context of the current command line being completed.

**Comment by unicornsasfuel** [comment]
Given that ishell is released under the MIT license, I suppose we could simply modify ishell to give args() access to the command line and then we wouldn't have to do silly things to get it to work the way we want.

**Comment by unicornsasfuel** [comment]
Having posted an enhancement request [here](https://github.com/italorossi/ishell/issues/17) I got the response from ishell's author that `readline.get_line_buffer()` should provide the line context necessary to do bash-style filepath completion in conjunction with `glob.glob()`.

**Comment by unicornsasfuel** [comment]
Okay, now that I've almost entirely rewritten the UI to use `ishell`, it still doesn't address the original request to support tab completion for paths, but `readline` and `glob` should allow you to do that.

@drakes00 would you be willing to write path tab completion into FeatherDuster as you mentioned earlier?

**Comment by drakes00** [comment]
Yes, I will try.
Thanks for the interface modification.

Le sam. 28 mai 2016 00:38, unicornsasfuel <notifications@github.com> a
écrit :

> Okay, now that I've almost entirely rewritten the UI to use ishell, it
> still doesn't address the original request to support tab completion for
> paths, but readline and glob should allow you to do that.
>
> @drakes00 <https://github.com/drakes00> would you be willing to write
> path tab completion into FeatherDuster as you mentioned earlier?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/nccgroup/featherduster/issues/15#issuecomment-222268300>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB253kYTARiYUYNjM0aFAVDrP0acqVwaks5qF3JNgaJpZM4IoTYs>
> .
>
-- 
--
Maxime Puys,
2nd year PhD Student in computer science,
VERIMAG, Univ. of Grenoble Alpes.
http://www-verimag.imag.fr/~puys/

**Comment by unicornsasfuel** [comment]
Closed as implemented, thanks @drakes00!
