### ISSUE TITLE
Write unit tests for FeatherDuster and its modules

### ISSUE THREAD

**Issue by unicornsasfuel** [nccgroup/featherduster#5]
Currently, no unit tests exist for FeatherDuster or its modules.

**Comment by unicornsasfuel** [comment]
This is on hold until issue #19 is resolved.

**Comment by unicornsasfuel** [comment]
This really shouldn't be marked "enhancement", complete sets of unit tests should be present in any mature software project.

**Comment by frankcash** [comment]
I wrote a feature to add  travis-ci support but currently the tests rely on user input

**Comment by unicornsasfuel** [comment]
Thanks @frankcash! Some of the tests can be easily converted to not require user input. However, there are some tests which are a bit tough to remove user input from, namely things which have a statistical chance of success like the multi-byte-xor cracker. The two ways I see to approach this are:

* Set a standard for success where we measure how close the attack comes to recovering the exact plaintext for our test sample.
* Provide a sample which is large enough that the statistical attack should always recover the entire text.

I've been avoiding both of these options because they both mean setting a standard for how much of the plaintext is successfully recovered, and I don't know a way to set that standard except for picking an arbitrary number. Plus, the statistical attacks should have a much better success rate with larger samples, so it'd have to be a standard we set for a particular size of sample. I'm not actually sure there's any precedent for this either, since breaking crypto is usually like "look, we recovered half the plaintext successfully, fix your code".

I'll work on the tests that don't have this problem.

**Comment by unicornsasfuel** [comment]
While FeatherDuster and its modules are still missing unit tests, having Travis-CI support helps create a framework to support those unit tests.

Moving forward, I think tests for FeatherDuster itself should probably be based on multi-line input redirection in bash

~~~bash
python featherduster.py <<EOF | grep "'hello'"
autopwn
import manualentry
gdkkn
autopwn
EOF
~~~

**Comment by unicornsasfuel** [comment]
This is the main issue I'd like to address with FeatherDuster. Going forward, I'd like tests for everything before making any releases. I'd also like FeatherDuster to be included in Kali Linux, and muts has requested that we have proper releases so that they know when we have reached a mature status and can be included in Kali.

**Comment by unicornsasfuel** [comment]
Tests have been written for FeatherDuster commands. Not surprisingly, a bug has been discovered (and fixed!) in the `unset` command as a result of having proper unit tests.
