### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by gleblanc1783** [nccgroup/featherduster#63]
I've been really digging featherduster since I originally saw it. I've had to install it on a few boxes so far, and I thought that building it into a docker image and committing it to an internal repo would be helpful.

If there is interest, I will commit what I have here to my fork and will make a PR.

Building featherduster
-
``` 
git clone https://github.com/nccgroup/featherduster.git
cd featherduster && docker build .
```
Running Container
-
```
docker run -it my/featherduster
Welcome to FeatherDuster!

To get started, use 'import' to load samples.
Then, use 'analyze' to analyze/decode samples and get attack recommendations.
Next, run the 'use' command to select an attack module.
Finally, use 'run' to run the attack and see its output.

For a command reference, press Enter on a blank line.


FeatherDuster>
```
Mounting local volume so you can load files
-
```
docker run -it -v ${PWD}:/data --entrypoint "python /opt/featherduster/featherduster.py file1.dat" my/featherduster 
```
**Note:** the files you want to look at must exist in your current working directory

Thanks!

**Comment by unicornsasfuel** [comment]
I'm interested! If you'd like to dockerize FeatherDuster and submit a PR I'd be happy to merge it!

**Comment by unicornsasfuel** [comment]
PR merged! Thanks for the contribution!
