### ISSUE TITLE
Crash in many_time_pad_attack when there's only one input

### ISSUE THREAD

**Issue by jamchamb** [nccgroup/featherduster#72]
Crashes at 
 https://github.com/nccgroup/featherduster/blob/master/feathermodules/stream/many_time_pad.py#L7 when `plaintexts` is `False` because only one input is being analyzed.

**Comment by unicornsasfuel** [comment]
Got it. Looks like the module wasn't checking for the failure condition from the `cryptanalib.break_many_time_pad` function.

Thanks for reporting, this should now be fixed!
