### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by carlospolop** [nccgroup/featherduster#79]
I am trying to install featherduster but an error occurs:

$sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to featherduster.egg-info/requires.txt
writing featherduster.egg-info/PKG-INFO
writing top-level names to featherduster.egg-info/top_level.txt
writing dependency_links to featherduster.egg-info/dependency_links.txt
writing entry points to featherduster.egg-info/entry_points.txt
reading manifest file 'featherduster.egg-info/SOURCES.txt'
writing manifest file 'featherduster.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/featherduster
copying build/lib.linux-armv7l-2.7/featherduster/__init__.py -> build/bdist.linux-armv7l/egg/featherduster
copying build/lib.linux-armv7l-2.7/featherduster/featherduster.py -> build/bdist.linux-armv7l/egg/featherduster
copying build/lib.linux-armv7l-2.7/featherduster/advice.py -> build/bdist.linux-armv7l/egg/featherduster
copying build/lib.linux-armv7l-2.7/featherduster/completer.py -> build/bdist.linux-armv7l/egg/featherduster
creating build/bdist.linux-armv7l/egg/cryptanalib
copying build/lib.linux-armv7l-2.7/cryptanalib/modern.py -> build/bdist.linux-armv7l/egg/cryptanalib
copying build/lib.linux-armv7l-2.7/cryptanalib/__init__.py -> build/bdist.linux-armv7l/egg/cryptanalib
copying build/lib.linux-armv7l-2.7/cryptanalib/classical.py -> build/bdist.linux-armv7l/egg/cryptanalib
copying build/lib.linux-armv7l-2.7/cryptanalib/frequency.py -> build/bdist.linux-armv7l/egg/cryptanalib
copying build/lib.linux-armv7l-2.7/cryptanalib/helpers.py -> build/bdist.linux-armv7l/egg/cryptanalib
creating build/bdist.linux-armv7l/egg/feathermodules
creating build/bdist.linux-armv7l/egg/feathermodules/block
copying build/lib.linux-armv7l-2.7/feathermodules/block/__init__.py -> build/bdist.linux-armv7l/egg/feathermodules/block
copying build/lib.linux-armv7l-2.7/feathermodules/block/aes_key_brute.py -> build/bdist.linux-armv7l/egg/feathermodules/block
copying build/lib.linux-armv7l-2.7/feathermodules/block/http_padding_oracle.py -> build/bdist.linux-armv7l/egg/feathermodules/block
copying build/lib.linux-armv7l-2.7/feathermodules/block/ecb_cpa_decrypt.py -> build/bdist.linux-armv7l/egg/feathermodules/block
copying build/lib.linux-armv7l-2.7/feathermodules/block/generic_padding_oracle.py -> build/bdist.linux-armv7l/egg/feathermodules/block
creating build/bdist.linux-armv7l/egg/feathermodules/classical
copying build/lib.linux-armv7l-2.7/feathermodules/classical/vigenere.py -> build/bdist.linux-armv7l/egg/feathermodules/classical
copying build/lib.linux-armv7l-2.7/feathermodules/classical/__init__.py -> build/bdist.linux-armv7l/egg/feathermodules/classical
copying build/lib.linux-armv7l-2.7/feathermodules/classical/alpha_shift.py -> build/bdist.linux-armv7l/egg/feathermodules/classical
copying build/lib.linux-armv7l-2.7/feathermodules/classical/columnar_transposition.py -> build/bdist.linux-armv7l/egg/feathermodules/classical
copying build/lib.linux-armv7l-2.7/feathermodules/__init__.py -> build/bdist.linux-armv7l/egg/feathermodules
creating build/bdist.linux-armv7l/egg/feathermodules/hash
copying build/lib.linux-armv7l-2.7/feathermodules/hash/__init__.py -> build/bdist.linux-armv7l/egg/feathermodules/hash
copying build/lib.linux-armv7l-2.7/feathermodules/hash/pymd5.py -> build/bdist.linux-armv7l/egg/feathermodules/hash
copying build/lib.linux-armv7l-2.7/feathermodules/hash/hash_extend.py -> build/bdist.linux-armv7l/egg/feathermodules/hash
creating build/bdist.linux-armv7l/egg/feathermodules/auxiliary
copying build/lib.linux-armv7l-2.7/feathermodules/auxiliary/rand_time.py -> build/bdist.linux-armv7l/egg/feathermodules/auxiliary
copying build/lib.linux-armv7l-2.7/feathermodules/auxiliary/__init__.py -> build/bdist.linux-armv7l/egg/feathermodules/auxiliary
copying build/lib.linux-armv7l-2.7/feathermodules/auxiliary/base_n_solver.py -> build/bdist.linux-armv7l/egg/feathermodules/auxiliary
copying build/lib.linux-armv7l-2.7/feathermodules/auxiliary/hash_format_detect.py -> build/bdist.linux-armv7l/egg/feathermodules/auxiliary
creating build/bdist.linux-armv7l/egg/feathermodules/custom
copying build/lib.linux-armv7l-2.7/feathermodules/custom/__init__.py -> build/bdist.linux-armv7l/egg/feathermodules/custom
creating build/bdist.linux-armv7l/egg/feathermodules/stream
copying build/lib.linux-armv7l-2.7/feathermodules/stream/single_byte_xor.py -> build/bdist.linux-armv7l/egg/feathermodules/stream
copying build/lib.linux-armv7l-2.7/feathermodules/stream/__init__.py -> build/bdist.linux-armv7l/egg/feathermodules/stream
copying build/lib.linux-armv7l-2.7/feathermodules/stream/multi_byte_xor.py -> build/bdist.linux-armv7l/egg/feathermodules/stream
copying build/lib.linux-armv7l-2.7/feathermodules/stream/many_time_pad.py -> build/bdist.linux-armv7l/egg/feathermodules/stream
creating build/bdist.linux-armv7l/egg/feathermodules/pubkey
copying build/lib.linux-armv7l-2.7/feathermodules/pubkey/rsa_wiener.py -> build/bdist.linux-armv7l/egg/feathermodules/pubkey
copying build/lib.linux-armv7l-2.7/feathermodules/pubkey/__init__.py -> build/bdist.linux-armv7l/egg/feathermodules/pubkey
copying build/lib.linux-armv7l-2.7/feathermodules/pubkey/rsa_fermat.py -> build/bdist.linux-armv7l/egg/feathermodules/pubkey
byte-compiling build/bdist.linux-armv7l/egg/featherduster/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-armv7l/egg/featherduster/featherduster.py to featherduster.pyc
byte-compiling build/bdist.linux-armv7l/egg/featherduster/advice.py to advice.pyc
byte-compiling build/bdist.linux-armv7l/egg/featherduster/completer.py to completer.pyc
byte-compiling build/bdist.linux-armv7l/egg/cryptanalib/modern.py to modern.pyc
byte-compiling build/bdist.linux-armv7l/egg/cryptanalib/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-armv7l/egg/cryptanalib/classical.py to classical.pyc
byte-compiling build/bdist.linux-armv7l/egg/cryptanalib/frequency.py to frequency.pyc
byte-compiling build/bdist.linux-armv7l/egg/cryptanalib/helpers.py to helpers.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/block/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/block/aes_key_brute.py to aes_key_brute.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/block/http_padding_oracle.py to http_padding_oracle.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/block/ecb_cpa_decrypt.py to ecb_cpa_decrypt.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/block/generic_padding_oracle.py to generic_padding_oracle.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/classical/vigenere.py to vigenere.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/classical/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/classical/alpha_shift.py to alpha_shift.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/classical/columnar_transposition.py to columnar_transposition.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/hash/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/hash/pymd5.py to pymd5.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/hash/hash_extend.py to hash_extend.pyc
  File "build/bdist.linux-armv7l/egg/feathermodules/hash/hash_extend.py", line 11
    def generate_hash_padding(original_plaintext, endianness='little')
                                                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-armv7l/egg/feathermodules/auxiliary/rand_time.py to rand_time.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/auxiliary/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/auxiliary/base_n_solver.py to base_n_solver.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/auxiliary/hash_format_detect.py to hash_format_detect.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/custom/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/stream/single_byte_xor.py to single_byte_xor.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/stream/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/stream/multi_byte_xor.py to multi_byte_xor.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/stream/many_time_pad.py to many_time_pad.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/pubkey/rsa_wiener.py to rsa_wiener.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/pubkey/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-armv7l/egg/feathermodules/pubkey/rsa_fermat.py to rsa_fermat.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying featherduster.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying featherduster.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying featherduster.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying featherduster.egg-info/entry_points.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying featherduster.egg-info/not-zip-safe -> build/bdist.linux-armv7l/egg/EGG-INFO
copying featherduster.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying featherduster.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
creating 'dist/featherduster-0.3-py2.7.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing featherduster-0.3-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/featherduster-0.3-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/featherduster-0.3-py2.7.egg
Extracting featherduster-0.3-py2.7.egg to /usr/local/lib/python2.7/dist-packages
  File "/usr/local/lib/python2.7/dist-packages/featherduster-0.3-py2.7.egg/feathermodules/hash/hash_extend.py", line 11
    def generate_hash_padding(original_plaintext, endianness='little')
                                                                     ^
SyntaxError: invalid syntax

featherduster 0.3 is already the active version in easy-install.pth
Installing featherduster script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/featherduster-0.3-py2.7.egg
Processing dependencies for featherduster==0.3
Searching for readline
Reading https://pypi.python.org/simple/readline/
Downloading https://pypi.python.org/packages/f4/01/2cf081af8d880b44939a5f1b446551a7f8d59eae414277fd0c303757ff1b/readline-6.2.4.1.tar.gz#md5=578237939c81fdbc2c8334d168b17907
Best match: readline 6.2.4.1
Processing readline-6.2.4.1.tar.gz
Writing /tmp/easy_install-_zqoJz/readline-6.2.4.1/setup.cfg
Running readline-6.2.4.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_zqoJz/readline-6.2.4.1/egg-dist-tmp-d5PSat
/usr/bin/ld: cannot find -lncurses
collect2: error: ld returned 1 exit status
error: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

Do you know what should I have to do??

**Comment by unicornsasfuel** [comment]
It looks like you don't have ncurses installed. There are instructions on how to address this here:

https://github.com/nccgroup/featherduster/blob/master/INSTALL.md#missing-libncurses

I believe this should fix your installation problem so I'm closing this issue, but feel free to comment again if it doesn't fix it for you.

Thanks for using FeatherDuster!
