### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [nccgroup/featherduster#89]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine cryptanalib/classical.py and observe `overfow`, however expect to see `overflow`.
- Examine cryptanalib/helpers.py and observe `occurance`, however expect to see `occurrence`.
- Examine cryptanalib/classical.py and observe `neccessary`, however expect to see `necessary`.
- Examine cryptanalib/modern.py and observe `mutiplier`, however expect to see `multiplier`.
- Examine tests/testbench_vigenere.py and observe `lenght`, however expect to see `length`.
- Examine cryptanalib/modern.py and observe `interger`, however expect to see `integer`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/featherduster/pull/new/bugfix_typos

Thanks.

**Comment by unicornsasfuel** [comment]
Thanks for the typo fixes!
