### ISSUE TITLE
ImportError: No module named ishell.console

### ISSUE THREAD

**Issue by Jugulaire** [nccgroup/featherduster#93]
I did install the tools following the INSTALL.md file : 

```bash
$ git clone https://github.com/nccgroup/featherduster.git
$ cd featherduster
$ pip install .
```

But after trying to lauch the tool i get this error : 
```
python featherduster/featherduster.py ../encrypted.txt
Traceback (most recent call last):
  File "featherduster/featherduster.py", line 13, in <module>
    from ishell.console import Console
ImportError: No module named ishell.console
```

I'm on Kali linux

**Comment by unicornsasfuel** [comment]
It looks like the ishell dependency failed to install, though I'm not sure why this would be. Can you try running `pip install ishell` and try again?

**Comment by unicornsasfuel** [comment]
Since there's been no response for months, I assume you have sorted this out.
