### ISSUE TITLE
Cant get featherduster to run kali 2021

### ISSUE THREAD

**Issue by bigPwn** [nccgroup/featherduster#94]
ive tried installing it with pip install . and it installs fine but the when i run the program it wants to use a env from python3 im guessing because it gives error with the print statements. When i install it with python setup.py install it also installs but when i try to run it with python featherduster/featherduster.py it gives error saying it cant find the feathermodules...which are in the same dir? Any help would be appreciated!

**Comment by unicornsasfuel** [comment]
Yes, featherduster relies on Python2.x, which has been deprecated. If you have Python2.x installed, you may be able to run it with `python2 featherduster/featherduster.py`. Most Linux distros have made the default Python environment a Python3 environment.

There is a port of the core module, cryptanalib, available as cryptanalib3. However, the console has not been ported to Python3 yet. You can use the analysis engine and attack functions from a Python3 console with it:

https://github.com/unicornsasfuel/cryptanalib3

You can also install it with pip3 like so: `pip3 install cryptanalib3`
